
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

frontend:
  themes: !include_dir_merge_named themes
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: home_assistant
  username: home_assistant
  password: !secret my_password
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - friendly_name
    - hidden
  exclude:
    domains:
      - automation
      - group

# Sensors
sensor:
  - platform: dsmr_reader